// Code generated by go-swagger; DO NOT EDIT.

// Package server Self-hosted HIBP password hash checker
//
//  Self-hosted HIBP password hash checker
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: latest
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/plain
//
// swagger:meta
package server
